version: "3.7"

services:
  prometheus:
    image: prom/prometheus:v2.2.1
    container_name: prometheus
    volumes:
      - ../PrometheusGrafana/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - 9090
    ports:
      - "9090:9090"

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    expose:
      - 9091
    ports:
      - "9091:9091"
  
  script_exporter:
    command:
      - '-config.file=/examples/config.yaml'
      - '-web.listen-address=:9469'
    container_name: 'script_exporter'
    network_mode: 'host'
    image: 'ricoberger/script_exporter:v2.5.2'
    ports:
      - '9469:9469'
    volumes:
      - './script_exporter/examples:/examples'
